export enum OpCode {
  NEGATE,
  LOGICAL_NOT,
  ADD,
  SUBTRACT,
  MULTIPLY,
  DIVIDE,
  LT,
  LTE,
  GT,
  GTE,
  EQ,
  NEQ,
  LOGICAL_OR,
  LOGICAL_AND,
  PUSH_CONSTANT,
  JUMP_FORWARD_IF_POP_FALSE,
  JUMP_FORWARD,
  JUMP_BACKWARD,
  JUMP_BOOLEAN_OR,  // if false, pop, else jump without popping
  JUMP_BOOLEAN_AND, // if true, pop, else jump without popping
  ASSIGN_CALLFRAME_VALUE,
  PUSH_CALLFRAME_VALUE,
  PUSH_CLOSURE,
  POP,
  CLOSE_VAR,
  CALL,
  RETURN,
  PUSH_EXTERNAL,
  CODESTOP, // used by decompiler!
};
